TW27065
eclipse-osee/org.eclipse.osee pull request #15
Opened 2024-09-10 20:55 UTC by vaibhavypatel

2024-09-10 21:19 UTC, jadenpuckett requested changes
Should do a rebase instead of a merge branch. Merge branch puts an unnecessary commit in the history.

2024-09-10 21:26 UTC, Grumb1e commented
I believe that is only the case if you do a rebase merge. If you do a squash merge it will collapse into one commit. You will just have to be careful with what name github gives the resulting commit.

2024-09-10 21:29 UTC, jadenpuckett approved these changes

2024-09-10 21:31 UTC, jadenpuckett commented
Alright. As long as the name of the squashed commit message is the proper name and not the merge branch commit name.

2024-09-11 16:09 UTC, dondunne commented on plugins/org.eclipse.osee.framework.ui.skynet/src/org/eclipse/osee/framework/ui/skynet/widgets/XWidget.java
> +   protected IUserGroupArtifactToken userGroupTok = UserGroupArtifactToken.SENTINEL;
remove "Tok" from field and methods

2024-09-11 16:09 UTC, dondunne commented on plugins/org.eclipse.osee.framework.ui.skynet/src/org/eclipse/osee/framework/ui/skynet/widgets/XWidget.java
> +   public IUserGroupArtifactToken getUserGroupTok() {
remove Tok

2024-09-16 15:41 UTC, dondunne approved these changes

2024-09-16 15:57 UTC, merged